### ISSUE TITLE
remove orphaned _cov argument from normalLhs sampling

### ISSUE THREAD

**Issue by ClaasRostock** [dnv-opensource/farn#19]
sampling.py: _generate_samples_using_normal_lhs_sampling() still foresees that a user can specify a "_cov" argument within the sampling parameters. However, to this option is not implemeted in the code, and to my knowledge we nowhere use it in demos or production code.  I hence propose to remove the optional "_cov" argument from normalLhs sampling.

@frl000: Any opinion from your end?

**Comment by frl000** [comment]
My intention was to implement it in future to make it complete. As long as is not used by anyone, we can remove it. At least in combination with covRes for gp it could simplify things because the distribution can then be hand-over "biased" from covRes. But I didn't use it because of better code understanding. In short: remove.
